In [1]:
#Autograd-- BAck prpoagation steps when training in neural networks to  calculate gradient with respect to parameters.

In [2]:
import torch

In [3]:
a = torch.tensor([5.],requires_grad=True)
b = torch.tensor([6.],requires_grad=True)

In [4]:
a

tensor([5.], requires_grad=True)

In [5]:
b

tensor([6.], requires_grad=True)

In [6]:
y = a**3-b**2

In [7]:
y # grad function assocaited with y

tensor([89.], grad_fn=<SubBackward0>)

In [9]:
# dy/da = 3*a**2 = 3 * 5 * 5 = 75
# dy/db = - 2b = -2 * 6 = -12
#Using Autograd we can compuute above loss automatically

In [12]:
print(a.grad)
print(b.grad)

None
None


In [13]:
y.backward()

In [14]:
print(a.grad)
print(b.grad)

tensor([75.])
tensor([-12.])


In [16]:
W = torch.randn(10,1,requires_grad=True)
B = torch.randn(1,requires_grad=True)

In [18]:
B

tensor([0.8061], requires_grad=True)

In [19]:
X = torch.rand(1,10)

In [21]:
op = torch.matmul(X,W) + B

In [22]:
loss = 1 - op

In [23]:
loss

tensor([[-3.6902]], grad_fn=<RsubBackward1>)

In [24]:
op

tensor([[4.6902]], grad_fn=<AddBackward0>)

In [25]:
loss.backward()

In [27]:
W.grad

tensor([[-0.1209],
        [-0.1597],
        [-0.8491],
        [-0.2841],
        [-0.7266],
        [-0.8960],
        [-0.5203],
        [-0.5362],
        [-0.4856],
        [-0.9779]])

In [28]:
with torch.no_grad():
    W = W - 0.001 * W.grad.data   

In [29]:
W

tensor([[ 0.6983],
        [-1.4296],
        [ 2.2826],
        [ 0.6803],
        [ 0.6407],
        [ 0.1624],
        [ 1.0997],
        [-0.0622],
        [ 1.6359],
        [-0.0449]])