In [2]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
from torchvision.transforms import transforms

/opt/anaconda3/envs/genai/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# Basic Autograd example
x = torch.tensor(data=1.,requires_grad=True)
w = torch.tensor(data=2.,requires_grad=True)
b = torch.tensor(data=3.,requires_grad=True)

In [5]:
# build computational graph y = WX+B

y = w * x + b

In [7]:
# compute gradients
y.backward()

In [8]:
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [22]:
#### basic autograd example 2
x = torch.randn(10,3) # 10 rows 3 columns
y = torch.randn(10,2)


In [23]:
# Build a fully connected layer
linear = nn.Linear(3,2)
print(linear.weight , "w")
print(linear.bias,"b")

Parameter containing:
tensor([[-0.2900,  0.0445, -0.4112],
        [-0.0488,  0.4766,  0.4359]], requires_grad=True) w
Parameter containing:
tensor([-0.0854,  0.4233], requires_grad=True) b


In [24]:
criterion = nn.MSELoss()
optimiser = torch.optim.SGD(linear.parameters(),lr=0.01)

In [25]:
pred = linear(x)

In [26]:
loss = criterion(pred,y)

In [29]:
loss.backward()

In [30]:
print(linear.weight.grad)
print(linear.bias.grad)

tensor([[-0.3725,  0.0541, -0.0801],
        [-0.0959,  0.4739,  0.2560]])
tensor([-0.0747,  0.3562])


In [31]:
optimiser.step()

In [32]:
pred = linear(x)
loss = criterion(pred,y)
print(f"loss after 1 step",loss.item())

loss after 1 step 1.353209137916565
